### ISSUE TITLE
Add `nlbq serve`

### ISSUE THREAD

**Issue by tomdyson** [torchbox/nlbq#3]
`nlbq serve` - starts an API server, similar to [nldb](https://github.com/tomdyson/nldb).

**Comment by tomdyson** [comment]
underway, see https://github.com/torchbox/nlbq/commit/b446e6e0eab32826e68e13ad450331cc3c4bf75b

**Comment by zerolab** [comment]
I think the one thing we are missing is an updated index.html template that makes use of the "dry-run then execute" flow
